const colors = {
  navBackground: '#25293a',
};

const sizes = {
  maxWidth: '1920px',
  mediaSmallWidth: '1600px',
  mediaMaxWidth: '1400px',
  mediaQHDWidth: '2000px',
  mediaMobileWidth: '900px',
  headerHeight: '90px',
  footerHeight: '80px',
};

const urls = {
  tierList: [
    process.env.PUBLIC_URL + '/images/img_tier_1.png',
    process.env.PUBLIC_URL + '/images/img_tier_2.png',
    process.env.PUBLIC_URL + '/images/img_tier_3.png',
    process.env.PUBLIC_URL + '/images/img_tier_4.png',
    process.env.PUBLIC_URL + '/images/img_tier_5.png',
  ],
  stageTierList: [
    {
      enable: process.env.PUBLIC_URL + '/images/img_stage_tier_1_enable.png',
      disable: process.env.PUBLIC_URL + '/images/img_stage_tier_1_disable.png',
    },
    {
      enable: process.env.PUBLIC_URL + '/images/img_stage_tier_2_enable.png',
      disable: process.env.PUBLIC_URL + '/images/img_stage_tier_2_disable.png',
    },
    {
      enable: process.env.PUBLIC_URL + '/images/img_stage_tier_3_enable.png',
      disable: process.env.PUBLIC_URL + '/images/img_stage_tier_3_disable.png',
    },
    {
      enable: process.env.PUBLIC_URL + '/images/img_stage_tier_4_enable.png',
      disable: process.env.PUBLIC_URL + '/images/img_stage_tier_4_disable.png',
    },
    {
      enable: process.env.PUBLIC_URL + '/images/img_stage_tier_5_enable.png',
      disable: process.env.PUBLIC_URL + '/images/img_stage_tier_5_disable.png',
    },
  ],
  stageGoal: process.env.PUBLIC_URL + '/images/img_stage_goal.png',
  stageGoalEffect: process.env.PUBLIC_URL + '/images/img_stage_goal_effect.png',
  stageRewardEffect: process.env.PUBLIC_URL + '/images/img_stage_reward_effect.png',
  tierBg: process.env.PUBLIC_URL + '/images/img_tier_bg_blank.png',
  tierBgActive: process.env.PUBLIC_URL + '/images/img_tier_bg_active.png',
  tierCoin: process.env.PUBLIC_URL + '/images/img_tier_coin.png',
  up: process.env.PUBLIC_URL + '/images/img_up.png',
  backArrow: process.env.PUBLIC_URL + '/images/ic_back_arrow.png',
  square: process.env.PUBLIC_URL + '/images/ic_square.png',
  square2: process.env.PUBLIC_URL + '/images/ic_square2.png',
  achievementList: [
    {
      enable: process.env.PUBLIC_URL + '/images/img_badge_bronze.png',
      disable: process.env.PUBLIC_URL + '/images/img_badge_bronze_disable.png',
    },
    {
      enable: process.env.PUBLIC_URL + '/images/img_badge_silver.png',
      disable: process.env.PUBLIC_URL + '/images/img_badge_silver_disable.png',
    },
    {
      enable: process.env.PUBLIC_URL + '/images/img_badge_gold.png',
      disable: process.env.PUBLIC_URL + '/images/img_badge_gold_disable.png',
    },
    {
      enable: process.env.PUBLIC_URL + '/images/img_badge_platinum.png',
      disable: process.env.PUBLIC_URL + '/images/img_badge_platinum_disable.png',
    },
    {
      enable: process.env.PUBLIC_URL + '/images/img_badge_diamond.png',
      disable: process.env.PUBLIC_URL + '/images/img_badge_diamond_disable.png',
    },
    {
      enable: process.env.PUBLIC_URL + '/images/img_medal_udc.png',
      disable: process.env.PUBLIC_URL + '/images/img_medal_udc_disable.png',
    },
    {
      enable: process.env.PUBLIC_URL + '/images/img_medal_bwb.png',
      disable: process.env.PUBLIC_URL + '/images/img_medal_bwb_disable.png',
    },
    {
      enable: process.env.PUBLIC_URL + '/images/img_medal_dmts.png',
      disable: process.env.PUBLIC_URL + '/images/img_medal_dmts_disable.png',
    },
  ],
  external: process.env.PUBLIC_URL + '/images/ic_external.svg',
  hudHoverLeft: process.env.PUBLIC_URL + '/images/img_hud_message_left.png',
  hudHoverCenter: process.env.PUBLIC_URL + '/images/img_hud_message_center.png',
  hudHoverRight: process.env.PUBLIC_URL + '/images/img_hud_message_right.png',
  hudIconMobile: process.env.PUBLIC_URL + '/images/img_hud_mobile.png',
  hudIconMobileAchievement: process.env.PUBLIC_URL + '/images/img_archievement_mobile.png',
  hudIconMobileMission: process.env.PUBLIC_URL + '/images/img_mission_mobile.png',
  hudIconMobileShop: process.env.PUBLIC_URL + '/images/img_shop_mobile.png',
  hudIconMobileStaking: process.env.PUBLIC_URL + '/images/img_staking_mobile.png',

  floatingKoa: process.env.PUBLIC_URL + '/images/img_floating_koa.gif',
  floatingKoaMessage: process.env.PUBLIC_URL + '/images/img_floatingkoa_messagebox.png',
  clearBg1: process.env.PUBLIC_URL + '/images/img_clear_bg1.png',
  clearBg2: process.env.PUBLIC_URL + '/images/img_clear_bg2.png',
  clearBg3: process.env.PUBLIC_URL + '/images/img_clear_bg3.png',
  clearBg4: process.env.PUBLIC_URL + '/images/img_clear_bg4.png',
  clearBg5: process.env.PUBLIC_URL + '/images/img_clear_bg5.png',
  clearBg6: process.env.PUBLIC_URL + '/images/img_clear_bg6.png',
  clearBg7: process.env.PUBLIC_URL + '/images/img_clear_bg7.png',
  staking: process.env.PUBLIC_URL + '/images/img_staking.png',
  stakingHover: process.env.PUBLIC_URL + '/images/img_staking_hover.png',
  shop: process.env.PUBLIC_URL + '/images/img_shop.png',
  shopHover: process.env.PUBLIC_URL + '/images/img_shop_hover.png',
  quizIcon: process.env.PUBLIC_URL + '/images/ic_quiz.png',
  bead: process.env.PUBLIC_URL + '/images/ic_bead.png',
  torch: process.env.PUBLIC_URL + '/images/img_torch.gif',
  koa: process.env.PUBLIC_URL + '/images/ic_koa.png',
  koaSpin: process.env.PUBLIC_URL + '/images/img_koa_spin.gif',
  diamond: process.env.PUBLIC_URL + '/images/img_diamond.png',
  fct: process.env.PUBLIC_URL + '/images/ic_fct.png',
  fctPixcel: process.env.PUBLIC_URL + '/images/img_fct_pixel.png',
  headerLogo: process.env.PUBLIC_URL + '/images/img_header_logo.svg',
  headerLogoMobile: process.env.PUBLIC_URL + '/images/img_header_logo2.svg',
  headerEcosystem: process.env.PUBLIC_URL + '/images/ic_ecosystem.svg',
  sideHudBox: process.env.PUBLIC_URL + '/images/img_side_hud_box.png',
  rewardIcon: process.env.PUBLIC_URL + '/images/ic_reward.svg',
  achieveIcon: process.env.PUBLIC_URL + '/images/ic_achievement.png',
  titleLogo: process.env.PUBLIC_URL + '/images/img_title_logo.png',
  titleLogo2: process.env.PUBLIC_URL + '/images/img_title_logo2.svg',
  titleLogoMobile: process.env.PUBLIC_URL + '/images/img_title_logo_mobile.png',
  titleLogoMobile2: process.env.PUBLIC_URL + '/images/img_title_logo_mobile2.svg',
  profile: process.env.PUBLIC_URL + '/images/img_profile.png',
  missionIcon: process.env.PUBLIC_URL + '/images/ic_mission.png',
  close: process.env.PUBLIC_URL + '/images/ic_close.svg',
  close2: process.env.PUBLIC_URL + '/images/ic_close2.png',
  closePixel: process.env.PUBLIC_URL + '/images/ic_close.png',
  back: process.env.PUBLIC_URL + '/images/ic_back.svg',
  storeApple: process.env.PUBLIC_URL + '/images/ic_apple.png',
  storeGoogle: process.env.PUBLIC_URL + '/images/ic_google.png',
  qrBg: process.env.PUBLIC_URL + '/images/img_qr_bg.png',
  wcFirma: process.env.PUBLIC_URL + '/images/ic_wc_firma.svg',
  wcQR: process.env.PUBLIC_URL + '/images/ic_wc_qr.svg',
  headerFCT: process.env.PUBLIC_URL + '/images/ic_header_fct.svg',
  refresh: process.env.PUBLIC_URL + '/images/ic_refresh.png',
  messageBox: process.env.PUBLIC_URL + '/images/img_message_box.png',
  messageBoxMobile: process.env.PUBLIC_URL + '/images/img_messagebox_mobile.png',
  messageBoxGoalMobile: process.env.PUBLIC_URL + '/images/img_messagebox_goal_mobile.png',
  messageBoxTop: process.env.PUBLIC_URL + '/images/img_message_box_top.png',
  messageBoxMiddle: process.env.PUBLIC_URL + '/images/img_message_box_middle.png',
  messageBoxBottom: process.env.PUBLIC_URL + '/images/img_message_box_bottom.png',
  modalCorner: process.env.PUBLIC_URL + '/images/img_modal_corner.png',
  sword: process.env.PUBLIC_URL + '/images/img_sword.svg',
  buttonLeft: process.env.PUBLIC_URL + '/images/img_btn_left.png',
  buttonRight: process.env.PUBLIC_URL + '/images/img_btn_right.png',
  buttonCenter: process.env.PUBLIC_URL + '/images/img_btn_center.png',
  plate: process.env.PUBLIC_URL + '/images/img_plate.png',
  timer: process.env.PUBLIC_URL + '/images/ic_timer.png',
  copy: process.env.PUBLIC_URL + '/images/ic_copy.svg',
  logout: process.env.PUBLIC_URL + '/images/ic_logout.svg',
  missionListItemBg: process.env.PUBLIC_URL + '/images/img_mission_list_item_bg.png',
  missionListSubBg: process.env.PUBLIC_URL + '/images/img_mission_list_sub_label.png',
  achievementListItemBg: process.env.PUBLIC_URL + '/images/img_achievement_list_item_bg.png',
  lock: process.env.PUBLIC_URL + '/images/ic_lock.png',
  check: process.env.PUBLIC_URL + '/images/ic_check.png',
  check2: process.env.PUBLIC_URL + '/images/ic_check2.png',
  ratingStar: process.env.PUBLIC_URL + '/images/img_rating_star.png',
  ratingStarEmpty: process.env.PUBLIC_URL + '/images/img_rating_star_empty.png',
  cloud: process.env.PUBLIC_URL + '/images/img_cloud.png',
  cloud4: process.env.PUBLIC_URL + '/images/img_cloud4.png',
  cloud5: process.env.PUBLIC_URL + '/images/img_cloud5.png',
  coin: process.env.PUBLIC_URL + '/images/img_coin.png',
  grass: process.env.PUBLIC_URL + '/images/img_grass.png',
  grassMobile: process.env.PUBLIC_URL + '/images/img_grass_mobile.png',
  fance: process.env.PUBLIC_URL + '/images/img_fance.png',
  road: process.env.PUBLIC_URL + '/images/img_road.png',
  roadMobile: process.env.PUBLIC_URL + '/images/img_road_mobile.png',
  missionBoard: process.env.PUBLIC_URL + '/images/img_mission_board.png',
  firmaLogo: process.env.PUBLIC_URL + '/images/img_firma.svg',
  fctLogo: process.env.PUBLIC_URL + '/images/img_fct.svg',
  loadingLogo: process.env.PUBLIC_URL + '/images/img_loading_logo.svg',
  introChar: process.env.PUBLIC_URL + '/images/img_intro_char.png',
  introLabel: process.env.PUBLIC_URL + '/images/img_intro_label.png',
  introButtonBg: process.env.PUBLIC_URL + '/images/img_intro_button_bg.png',
  introPoweredFirma: process.env.PUBLIC_URL + '/images/img_powered_firma.png',
  signNormal: process.env.PUBLIC_URL + '/images/img_sign_normal.png',
  signHover: process.env.PUBLIC_URL + '/images/img_sign_hover.png',
  signNormal2: process.env.PUBLIC_URL + '/images/img_sign_normal2.png',
  signHover2: process.env.PUBLIC_URL + '/images/img_sign_hover2.png',
  sign2: process.env.PUBLIC_URL + '/images/img_sign_2.png',
  signMobile: process.env.PUBLIC_URL + '/images/img_sign_mobile.png',
  character1: process.env.PUBLIC_URL + '/images/img_char_1.gif',
  character2: process.env.PUBLIC_URL + '/images/img_char_2.gif',
  character3: process.env.PUBLIC_URL + '/images/img_char_3.gif',
  character4: process.env.PUBLIC_URL + '/images/img_char_4.gif',
  character5: process.env.PUBLIC_URL + '/images/img_char_5.gif',
  character6: process.env.PUBLIC_URL + '/images/img_char_6.png',
  character7: process.env.PUBLIC_URL + '/images/img_char_7.png',
  character8: process.env.PUBLIC_URL + '/images/img_char_8.png',
  character9: process.env.PUBLIC_URL + '/images/img_char_9.png',
  character10: process.env.PUBLIC_URL + '/images/img_char_10.png',
  character11: process.env.PUBLIC_URL + '/images/img_char_11.png',
  tree: process.env.PUBLIC_URL + '/images/img_tree.png',
  characterStone: process.env.PUBLIC_URL + '/images/img_stone.png',
  chest: process.env.PUBLIC_URL + '/images/img_chest.png',
  chest2: process.env.PUBLIC_URL + '/images/img_chest2.png',
  gem: process.env.PUBLIC_URL + '/images/img_gem.png',
  gemBox: process.env.PUBLIC_URL + '/images/img_gem_box.png',
  star: process.env.PUBLIC_URL + '/images/img_star.gif',
  worldBg: process.env.PUBLIC_URL + '/images/img_world.png',
  stageEnable: process.env.PUBLIC_URL + '/images/img_stage_enable.png',
  stageDisable: process.env.PUBLIC_URL + '/images/img_stage_disable.png',
  socialMedium: process.env.PUBLIC_URL + '/images/img_social_medium.svg',
  socialX: process.env.PUBLIC_URL + '/images/img_social_x.svg',
  socialTelegram: process.env.PUBLIC_URL + '/images/img_social_telegram.svg',
};

const theme = {
  colors,
  sizes,
  urls,
};

export default theme;
