export const HANDLE_WALLET_ADDRESS = 'HANDLE_WALLET_ADDRESS';

export const HANDLE_WALLET_BALANCE = 'HANDLE_WALLET_BALANCE';

export const HANDLE_WALLET_TOKEN_BALANCE = 'HANDLE_WALLET_TOKEN_BALANCE';
